function OutputMovie(obj,varargin)

%
% OutputMovie(obj,varargin)
% pairs={...
%   'aviname',   'output.avi';                                ...
%   'fps',       10;                                          ...
%   'frameinds', 1:500;                                       ...
%   't0',        [];                                          ...
%   'chunksize', 500;                                         ...
%   'fig',       [];                                          ...
%   'props',     [];                                          ... 
%   'txtpos',    [ceil(0.1*obj.Width) ceil(0.99*obj.Height)]; ...
%   'txtcolor',  [1 1 1];                                     ...
%   'txtsize',   16;                                          ...
%   'peh',       [];                                          ...
%   'sizemult',  2;                                           ...
%   };
% parseargs(varargin,pairs);
%

pairs={...
  'aviname',   'output.avi';                                ...
  'fps',       10;                                          ...
  'frameinds', 1:500;                                       ...
  't0',        [];                                          ...
  'chunksize', 500;                                         ...
  'fig',       [];                                          ...
  'props',     [];                                          ... 
  'txtpos',    [ceil(0.1*obj.Width) ceil(0.99*obj.Height)]; ...
  'txtcolor',  [1 1 1];                                     ...
  'txtsize',   16;                                          ...
  'peh',       [];                                          ...
  'sizemult',  2;                                           ...
  'MovieName', [];                                          ...
  };
parseargs(varargin,pairs);

if ~isempty(MovieName), obj.MovieName=fullpath(MovieName); end

chunks=obj.ChunkInds(frameinds(1),frameinds(length(frameinds)),chunksize);
nchunks=size(chunks,1);

% preliminary plot
if isempty(fig), fig=figure; else figure(fig); clf; end
figpos=get(fig,'position');
set(fig,'position',[figpos(1:2) sizemult*[obj.Width obj.Height]]);
himg=imagesc(zeros(obj.Height,obj.Width));
colormap gray;
set(gca,'clim',[0 255],'position',[0 0 1 1]);
if isempty(props)
  props.clr=[0.95 0.28 0.32];
  props.lw=4;
end
hell=ellipse(median(1:obj.Width),median(1:obj.Height),0.5*obj.Width,0.5*obj.Height,0,props);
htxt=text(txtpos(1),txtpos(2),sprintf('time %6.1f',0),'fontsize',txtsize,'color',txtcolor);
set(htxt,'horizontalalignment','left','verticalalignment','bottom','interpreter','none')
hphi=text(obj.Pos(1,1)-1.8*obj.Axs(1,1)*sin(pi*obj.Angle(1)/180), ...
          obj.Pos(2,1)+1.8*obj.Axs(2,1)*cos(pi*obj.Angle(1)/180), ...
          sprintf('phi = %3.1f',obj.Angle(1)), ...
          'color','r', 'fontsize',14, 'fontweight','bold', ...
          'verticalalignment','top', 'horizontalalignment','center' );
% hphi=text(10,10,sprintf('phi = %3.1f',obj.Angle(1)), 'color','r');
drawnow

% movie file
aviobj = avifile(aviname,'fps',fps);

for ich=1:nchunks
  
  % display chunk no
  fprintf('Working on chunk %d/%d.\n',ich,nchunks);
  
  % grab frames
  cframes=chunks(ich,1):chunks(ich,2);  
  obj.GrabFrames(cframes);
  
  % grab the 
  if ~isempty(peh), [epids,epnames]=ts2epoch(obj.FrameTimes+obj.T0,peh);
  else              epids=ones(1,numel(obj.FrameTimes)); epnames={'',''};
  end
  epids(epids==0)=max(epids)+1;
  epnames{end+1,1}='null';
  epnames{end+1,2}=max(epids);
  
  for k=1:obj.NFrames
    ind=cframes(k);
    set(himg,'CData',obj.Frames{k});
    delete(hell);
    hell=ellipse(obj.Pos(1,ind),obj.Pos(2,ind),obj.Axs(1,ind),obj.Axs(2,ind),90+obj.Angle(ind),props);
    epstring=epnames{epids(k),1};
    set(htxt,'string',sprintf('time %6.1f, %s',obj.FrameTimes(k),epstring));
    set(hphi,'position',...
      [obj.Pos(1,ind)-1.8*obj.Axs(1,ind)*sin(pi*obj.Angle(ind)/180)   ...
       obj.Pos(2,ind)+1.8*obj.Axs(2,ind)*cos(pi*obj.Angle(ind)/180)], ...
      'string',sprintf('phi = %3.1f',obj.Angle(ind)));
%     set(hphi,'string', sprintf('phi = %3.1f',obj.Angle(ind)) );
    drawnow;
    aviframe = getframe(gca);
    aviobj   = addframe(aviobj,aviframe);
  end
  
end

aviobj = close(aviobj);
