function [rw] = reserved_word_list
   
   rw = { ...
     'base_iti_state'         ...
     'current_state'          ...
     'entry'                  ...
     'i'                      ...
     'j'                      ...
     'resolve_schedwave_strs' ...
     'resolve_strs'           ...
     'sched_waves'            ...
     'sma'                    ...
     'state_names'            ...
     'stm'                    ...
     'str'                    ...
     'sw_outcol'              ...
     'TupCol'                 ...
     'starting_state'         ...
     'ending_state'           ...
     'pokes_starting_state'   ...
     'pokes_ending_state'     ...
     };
   