
% Version history
% 091905:   Carlos      Initial write
% 092105:   SSP         
%   - Added 'TooltipString', 'label' (in 'pairs'), labelpos
%   - EditParam returns itself as an object
% 092405:   SSP         Replaced old file with Carlos' versions and re-made
% changes made on 092105


function [ed] = TextBoxParam(obj, parname, parval, x, y, varargin)

   if ischar(obj) && strcmp(obj, 'base'), param_owner = 'base';
   elseif isobject(obj),                  param_owner = ['@' class(obj)];
   else   error('obj must be an object or the string ''base''');
   end;
   
   pairs = { ...
       'param_owner',        param_owner            ; ...
       'param_funcowner',    determine_fullfuncname     ; ...
       'position',           []                         ; ...
       'TooltipString',      ''                         ; ...
       'label',              parname                    ; ...
       'labelfraction',      0.5                        ; ...
       'labelpos',           'right'                    ; ...  
       'HorizontalAlignment' 'right'                    ; ...
       'nlines'              5                          ; ...
       }; parseargs(varargin, pairs);

   if isempty(position),
      position = gui_position(x, y);
      position(4) = position(4)*nlines;
   end;
   
   ed = SoloParamHandle(obj, parname, ...
                        'type',            'textbox', ...
                        'value',           parval, ...
                        'position',        position, ...
                        'TooltipString',   TooltipString, ...
                        'label',           label, ...
                        'labelfraction',   labelfraction, ...
                        'labelpos',        labelpos, ...
                        'HorizontalAlignment', HorizontalAlignment, ...
                        'nlines',          nlines, ...
                        'param_owner',     param_owner, ...
                        'param_funcowner', param_funcowner);
   assignin('caller', parname, eval(parname));
   return;
   
   
