function [cstr]=getSessInfo(sessid)

sql=['select  experimenter,  ratname , protocol, hostname  , ip_addr,   sessiondate,     starttime ,  endtime   ,'...
'	comments    , total_correct ,  right_correct ,  left_correct  , percent_violations,data_file from sessions where sessid="{Si}"'];

	
[  experimenter,  ratname , protocol, hostname  , ip_addr,  sessiondate,     starttime ,  endtime   ,...
	comments    , total_correct ,  right_correct ,  left_correct  , percent_violations,data_file]=bdata(sql,sessid);

cstr=sprintf(['SessID: %i   %s  %s\nExperimenter: %s,  Rat: %s,  Protocol : %s,\n'...
	'Date: %s,  Start: %s,  End: %s\n'...
	'Correct: %.1f%%,  Right Correct: %.1f%%,  Left Correct: %.1f%%\n'...
	'%% Violations: %.1f\nFilename: %s\n'...
	'Comments: %s\n'],...
	 sessid,hostname{1}  , ip_addr{1} ,experimenter{1},  ratname{1} , protocol{1},  sessiondate{1},     starttime{1} ,  endtime{1}   ,...
	 total_correct*100 ,  right_correct*100 ,  left_correct*100  , percent_violations*100,data_file{1},comments{1});