function [xpos] = barweb_change_colour(ahandle, clr,varargin)
% changes bars generated by 'barweb' subroutine to whichever
% colour you want.
% 'clr' must be in [r g b] format, not in string format
% optional 3rd param is edgecolor
%
% 
if length(varargin) > 0
    edgeclr = varargin{1};
    if length(varargin) == 2
        isarray = varargin{2};
    end;
end;


c = get(ahandle,'Children'); % all hggroup
ctr=0;
clrctr = 1;
xpos = [];
for k = 1:length(c)
    c2 = get(c(k),'Children');
    
    % found an hggroup with a child patch
     if length(c2) == 1 && strcmpi(get(c2(1), 'Type'), 'patch')
         ctr=ctr+1;
         pos = get(c2(1),'XData');
         fprintf(1,'found %i @ X=%2.2f\n', ctr, pos(1));
         xpos = horzcat(xpos, mean(pos(:,1)));
         set(c2(1),'FaceColor', clr{clrctr});
         if length(varargin)>0,
             set(c2(1), 'EdgeColor',edgeclr);
         end;
         clrctr = clrctr+1;
         % found hggroup with lines as children
     else 
         for k2 = 1:length(c2)
             set(c2(k2),'LineWidth',2);
         end;
     end;
end;