emaillist = {'A','asatty@Princeton.EDU' ,'Alex';...
             'B','bwen@Princeton.EDU'   ,'Bing';...
             'C','brody@Princeton.EDU'  ,'Carlos';...
             'K','ckopec@Princeton.EDU' ,'Chuck';...
             'J','jerlich@Princeton.EDU','Jeff';...
             'M','mbialek@Princeton.EDU','Max';...
             'T','tdhanks@u.washington.edu','Tim'};

techs = {'GB','glynb@Princeton.EDU',  'Glyn';...
         'KO','losorio@Princeton.EDU','Klaus'};
     
manager = {'SK','skarnup@Princeton.EDU','Sergei'};

%  emaillist = {'B','ckopec@Princeton.EDU','Bing';...
%               'C','ckopec@Princeton.EDU','Carlos';...
%               'K','ckopec@Princeton.EDU','Chuck';...
%               'J','ckopec@Princeton.EDU','Jeff';...
%               'M','ckopec@Princeton.EDU','Max'};
% 
% techs = {'GB','ckopec@Princeton.EDU','Glyn';...
%          'KO','ckopec@Princeton.EDU','Klaus'};
     