function [] = sessionsummary(action, varargin)
% Shortcut script that shows session summary for a rat

if nargin > 1
    action = varargin{2}; % callback
end;

global Solo_rootdir;
if isempty(Solo_rootdir), mystartup; end;
stat_dir = [Solo_rootdir filesep 'Analysis' filesep 'duration_disc' filesep 'stat_sandbox'];
event_analysis_dir = [Solo_rootdir filesep 'Analysis' filesep 'duration_disc' filesep 'Event_Analysis'];

if ~is_in_path(stat_dir)
    fprintf(1,'Adding stat_sandbox to path ...\n');
    addpath(stat_dir);
    addpath(event_analysis_dir);
end;

switch action
    case 'close'
        % Close all windows generated by this script
        taglist = {'sessionview','loadpsych','pokeviewer','sessionduration','dailyglimpse','dailypsych'};
        for currt = 1:length(taglist)
            f = findobj('Tag',taglist{currt});
            for k = 1:length(f)
                b = f(k);
                eval(sprintf('close %i', b));
            end;
        end;

        return;
    case 'exit'
        close all;
    case 'init'
        rat_table = rat_task_table('blah','get_current',1);
        ratlist = sort(rat_table(:,1));
        figure;
        ht = 700; clr = [255 206 86] ./255;
        hdr_clr = [53 109 86]./255; hdr_txt = [1 1 1];
        set(gcf,'Name','Behaviour View', 'Menubar','none', ...
            'Position',[20   181   400   ht],'Color',clr,'Tag','sessiondriver');

        x =80;
        y =ht-30;
        twidth = 60;
        h=uibuttongroup('Visible','on','Position',[0 0 0.01 0.01],'Tag','ropt');
        h1=uicontrol('STyle','radiobutton','String', 'all', 'Tag','ropt_all', 'Parent',h,'Position',[x y twidth 20],'BackgroundColor',clr);
        h2=uicontrol('STyle','radiobutton','String', 'current', 'Tag','ropt_current', 'Parent',h,'Position',[x+twidth y 1.5*twidth 20],'BackgroundColor',clr);

        % Initialize some button group properties.
        set(h,'SelectionChangeFcn',{'sessionsummary','change_roption'});
        set(h,'SelectedObject',h2);  % No selection
        set(h,'Visible','on');
        y=y-30;

        uicontrol('STyle','text','STring','Rat name:','Position',[20 y-5 twidth*2 20],'BackgroundColor',clr,'FontSize',16,'FontAngle','italic','FontWeight','bold');
        uicontrol('Style','popupmenu','Tag','ratname','String', ratlist,'Position',[130 y-10 200 30],'FontSize',16,'FontWeight','bold',...
            'ForegroundColor',[0.8 0.3 0],'BackgroundColor','w');
        y = y-30;
        h=uibuttongroup('Visible','on','Position',[0 0 0.01 0.01],'Tag','dopt');
        h1=uicontrol('STyle','radiobutton','String', 'offset', 'Tag','dopt_offset', 'Parent',h,'Position',[x y twidth 20],'BackgroundColor',clr);
        h2=uicontrol('STyle','radiobutton','String', 'date', 'Tag','dopt_date', 'Parent',h,'Position',[x+twidth y twidth 20],'BackgroundColor',clr);
        % Initialize some button group properties.
        set(h,'SelectionChangeFcn',{'sessionsummary','change_doption'});
        set(h,'SelectedObject',h1);  % No selection
        set(h,'Visible','on');

        y=y-30;
        uicontrol('STyle','text','STring',sprintf('Date\noffset:'),'Position',[20 y-20 twidth 40],'BackgroundColor',clr,'FontSize',12,'FontAngle','italic','FontWeight','bold');
        uicontrol('Style','edit','Tag','doffset','String', '-2','Position',[x y 30 20],'BackgroundCOlor', 'w');
        uicontrol('STyle','text','STring','Date','Position',[120 y+5 twidth 10],'BackgroundColor',clr,'FontSize',12,'FontAngle','italic','FontWeight','bold');
        uicontrol('Style','edit','Tag','date','String', [yearmonthday(now) 'a'],'Position',[ 180 y 50 20],'BackgroundCOlor', 'w');

        y = y-30;

        % ----------------------------------------------
        % Day-to-day monitoring
        % ----------------------------------------------

        uicontrol('Style','text','String', 'Daily monitoring', 'FontSize',14,'FontWeight','bold',...
            'Position', [20 y 350 17],'BackgroundColor',hdr_clr, 'ForegroundColor', hdr_txt);

        y=y-50;
        uicontrol('String', 'Drinking','Position',[270 y-60 60 30],'Callback',{'sessionsummary', 'dailydrink'},'FontWeight','bold');
        uicontrol('String', 'Timeouts','Position',[330 y-60 60 30],'Callback',{'sessionsummary', 'sessionto'},'FontWeight','bold');
        uicontrol('String', 'Correction','Position',[330 y-30 60 30],'Callback',{'sessionsummary', 'sessionbbspl'},'FontWeight','bold');

        uicontrol('String', 'Session summary','Position',[30 y 150 40],'Callback',{'sessionsummary', 'cbk_mode'},'FontSize',14,'FontWeight','bold');
        uicontrol('String', 'Psych curve','Position',[180 y-25 120 40],'Callback',{'sessionsummary', 'daypsych'},'FontSize',14,'FontWeight','bold');
        y = y-50;
        uicontrol('String', 'Pokes plot','Position',[30 y 150 40],'Callback',{'sessionsummary', 'showpokes'},'FontSize',14,'FontWeight','bold');
        uicontrol('String','close', 'Position', [350 y+70 40 25],'BackgroundColor',[240 186 112]./255,'Callback',{'sessionsummary','close'},'FontWeight','bold','FontAngle','italic');

        % ------------------------------------------------
        % Do something over a range of dates
        % ------------------------------------------------
        y=y-30;
        uicontrol('Style','text','String', 'Analyze over range of dates', 'FontSize',14,'FontWeight','bold',...
            'Position', [20 y 350 17],'BackgroundColor',hdr_clr, 'ForegroundColor', hdr_txt);
        y=y-30;

        % from/to dates
        uicontrol('STyle','text','STring','From:','Position',[50 y+5 twidth 10],'BackgroundColor',clr,'FontSize',12,'FontAngle','italic','FontWeight','bold');
        uicontrol('Style','edit','Tag','fromdate','String', '000000','Position',[110 y 50 20],'BackgroundCOlor', 'w');
        uicontrol('STyle','text','STring','To:','Position',[170 y+5 twidth 10],'BackgroundColor',clr,'FontSize',12,'FontAngle','italic','FontWeight','bold');
        uicontrol('Style','edit','Tag','todate','String', '999999','Position',[ 230 y 50 20],'BackgroundCOlor', 'w');

        y=y-30;
        uicontrol('String','# trials','Position',[20 y-10 100 30],'Callback',{'sessionsummary','numtrials'});
        uicontrol('String','Timeout rate','Position',[130 y-10 100 30],'Callback',{'sessionsummary','timeout_rate'});
        uicontrol('String','Trial length influence','Position',[230 y-10 150 30],'Callback',{'sessionsummary','triallen'});

        y=y-30;
        uicontrol('String','Indie psych curves','Position',[20 y-10 120 30],'Callback',{'sessionsummary','dailypsychs'});
        uicontrol('String','Pooled psych','Position',[150 y-10 100 30],'Callback',{'sessionsummary','pooledpsychs'});
        uicontrol('String','Psychnums','Position',[270 y-10 100 30],'Callback',{'sessionsummary','psychnums'});
        y=y-30;
        uicontrol('String','Psych endpoints','Position',[20 y-10 100 30],'Callback',{'sessionsummary','psychends'});
        uicontrol('String','Hit rate','Position',[150 y-10 100 30],'Callback',{'sessionsummary','sessionhrate'});

        % ------------------------------------------------
        % Psych data
        % ------------------------------------------------
        y=y-50;
        uicontrol('Style','text','String', 'Lesion Analysis', 'FontSize',14,'FontWeight','bold',...
            'Position', [20 y 350 17],'BackgroundColor',hdr_clr, 'ForegroundColor', hdr_txt);
        y=y-30;

        uicontrol('Style','popupmenu','String',{'before','after'},'Position',[130 y 1.5*twidth 10],'Tag','showpsych');
        uicontrol('String','Psych summary','Position',[20 y-10 100 30],'Callback',{'sessionsummary','showpsych'});
        uicontrol('String',sprintf('BEFORE/AFTER sig.'), 'Position',[240 y-20 150 50],'Callback',{'sessionsummary','surgeryeffect'},'FontSize',12,'FontWeight','bold');
        %                uicontrol('String',sprintf('BEFORE/AFTER sig (vanilla)'), 'Position',[200 y 150 50],'Callback',{'sessionsummary','surgeryeffect_log'});

        % ------------------------------------------------
        % Cannula analysis
        % ------------------------------------------------
        y=y-50;
        uicontrol('Style','text','String', 'Cannula analysis', 'FontSize',14,'FontWeight','bold',...
            'Position', [20 y 350 17],'BackgroundColor',hdr_clr, 'ForegroundColor', hdr_txt);
        y=y-20;
        uicontrol('Style','popupmenu','String',{'pool all days','don''t pool'},'Position',[20 y 2*twidth 10],'Tag','can__poolopt');
        uicontrol('Style','popupmenu','String',{'one_set_plot','two_sets_plot'},'Position',[180 y 2*twidth 10],'Tag','can__whichscpt');
        y=y-30;
        uicontrol('String','Baseline','Position',[20 y-10 100 30],'Callback',{'sessionsummary','can__baseline'});
        uicontrol('String','Base vs. single psych','Position',[150 y-10 150 30],'Callback',{'sessionsummary','can__singlepsych'});
        y=y-30;
        uicontrol('String','Nomanip','Position',[20 y-10 70 30],'Callback',{'sessionsummary','can__nomanip'});
        uicontrol('String','Muscimol','Position',[100 y-10 90 30],'Callback',{'sessionsummary','can__muscimol'});
     %   uicontrol('String','Muscimol+1','Position',[200 y-10 90 30],'Callback',{'sessionsummary','can__muscimolplusone'});        
        uicontrol('String','Saline','Position',[300 y-10 100 30],'Callback',{'sessionsummary','can__saline'});
        y=y-40;
        uicontrol('Style','text','String','Plot pairs:','Position',[10 y-10 twidth 20],'BackgroundColor',clr,'FontSize',12,'FontAngle','italic','FontWeight','bold');
        uicontrol('String','Noinf-Musc','Position',[80 y-10 100 30],'Callback',{'sessionsummary','can__noinf_musc'});
        uicontrol('String','Sal-Musc','Position',[190 y-10 100 30],'Callback',{'sessionsummary','can__sal_musc'});
        uicontrol('String','All three','Position',[300 y-10 100 30],'Callback',{'sessionsummary','can__all'});

        sessionsummary(0,0,'change_doption');

    case 'sessionto'
        % get ratname
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        % get date
        h = get(findobj('Tag','dopt'),'SelectedObject');
        if strcmpi(get(h,'Tag'),'dopt_offset')
            dobj = findobj('Tag', 'doffset'); d = str2double(get(dobj,'String'));
            dstr = getdate(d);
        else
            dstr = get(findobj('Tag','date'),'string');
        end;

        ratrow = rat_task_table(r{idx});
        timeout_count(r{idx},ratrow{1,2}, dstr);
        set(gcf,'Tag','sessionview');

    case 'dailydrink'
        % get ratname
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        % get date
        h = get(findobj('Tag','dopt'),'SelectedObject');
        if strcmpi(get(h,'Tag'),'dopt_offset')
            dobj = findobj('Tag', 'doffset'); d = str2double(get(dobj,'String'));
            dstr = getdate(d);
        else
            dstr = get(findobj('Tag','date'),'string');
        end;

        ratrow = rat_task_table(r{idx});
        licking_during_reward(r{idx}, dstr);
        set(gcf,'Tag','sessionview');
        
        
    case 'sessionbbspl'
        % get ratname
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        % get date
        h = get(findobj('Tag','dopt'),'SelectedObject');
        if strcmpi(get(h,'Tag'),'dopt_offset')
            dobj = findobj('Tag', 'doffset'); d = str2double(get(dobj,'String'));
            dstr = getdate(d);
        else
            dstr = get(findobj('Tag','date'),'string');
        end;

        session_corr(r{idx}, dstr);
        set(gcf,'Tag','sessionview');

    case 'cbk_mode'
        h = get(findobj('Tag','dopt'),'SelectedObject');
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        if strcmpi(get(h,'Tag'),'dopt_offset')
            dobj = findobj('Tag', 'doffset'); d = str2double(get(dobj,'String'));
            dstr = getdate(d);
        else
            dstr = get(findobj('Tag','date'),'string');
        end;
        tic
        session_view(r{idx},dstr);
        set(gcf,'Tag','sessionview');
        tm = toc;
        fprintf(1,'%1.2f seconds\n', tm);
        licking_during_reward(r{idx}, dstr);
        set(gcf,'Tag','sessionview','Position',[463 571 565 145]);
                

    case 'showpokes'
        h = get(findobj('Tag','dopt'),'SelectedObject');

        if strcmpi(get(h,'Tag'),'dopt_offset')
            dobj = findobj('Tag', 'doffset'); d = str2double(get(dobj,'String'));
            dstr = getdate(d);
        else
            dstr = get(findobj('Tag','date'),'string');
        end;
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        pokeviewer(r{idx},dstr,'init');
        set(gcf,'Menubar','figure');

    case 'change_doption'
        h = get(findobj('Tag','dopt'),'SelectedObject');
        if strcmpi(get(h,'Tag'),'dopt_offset')
            set(findobj('Tag','doffset'),'ENable','on');
            set(findobj('Tag','date'), 'Enable','off');
        else
            set(findobj('Tag','doffset'),'ENable','off');
            set(findobj('Tag','date'), 'Enable','on');
        end;

    case 'change_roption'
        h = get(findobj('Tag','ropt'),'SelectedObject');
        set(findobj('Tag','ratname'),'Value',1);
        if strcmpi(get(h,'Tag'),'ropt_all')
            ratlist = rat_task_table('','get_all',1);
        else
            ratlist = rat_task_table('','get_current',1);
        end;
        ratlist = sort(ratlist(:,1));
        set(findobj('Tag','ratname'),'String',ratlist);

    case 'showpsych'
        v = get(findobj('Tag','showpsych'),'value');
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');

        if v == 1
            loadpsychinfo(r{idx}, 'infile', 'psych_before');
        elseif v == 2
            loadpsychinfo(r{idx}, 'infile', 'psych_after');
        else
            error('Invalid value');
        end;

    case 'daypsych'
        h = get(findobj('Tag','dopt'),'SelectedObject');

        if strcmpi(get(h,'Tag'),'dopt_offset')
            dobj = findobj('Tag', 'doffset'); d = str2double(get(dobj,'String'));
            dstr = getdate(d);
        else
            dstr = get(findobj('Tag','date'),'string');
        end;

        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        psychometric_curve(r{idx},dstr);
%   compare_mypsych_psignifit(r{idx},dstr); 
%   set(gcf,'Menubar','figure');
%   k= get(gca,'Children'); set(k(4),'LineWidth',2);
         set(gcf,'Tag', 'dailypsych');

    case 'surgeryeffect'
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        surgery_effect(r{idx});

    case 'surgeryeffect_log'
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        surgery_effect_fixedlog(r{idx});


    case 'toneprog'
        h=get(findobj('Tag','dopt'),'SelectedObject');
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        if strcmpi(get(h,'Tag'),'dopt_offset')
            dobj = findobj('Tag', 'doffset'); d = str2double(get(dobj,'String'));
            dstr = getdate(d);
        else
            dstr = get(findobj('Tag','date'),'string');
        end;
        session_view(r{idx},dstr,'toneprog_only',1);

    case 'firstdaypost'
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        surgery_effect(r{idx},'first_day_post',1);

    case 'quickview'
        h = get(findobj('Tag','dopt'),'SelectedObject');

        if strcmpi(get(h,'Tag'),'dopt_offset')
            dobj = findobj('Tag', 'doffset'); d = str2double(get(dobj,'String'));
            dstr = getdate(d);
        else
            dstr = get(findobj('Tag','date'),'string');
        end;
        dailyglimpse_all(dstr);

    case  'numtrials'
        fromobj = findobj('Tag','fromdate'); from = get(fromobj,'String');
        toobj = findobj('Tag','todate'); to = get(toobj,'String');

        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        numtrials_oversessions(r{idx},'from', from, 'to',to);

    case  'sessionhrate'
        fromobj = findobj('Tag','fromdate'); from = get(fromobj,'String');
        toobj = findobj('Tag','todate'); to = get(toobj,'String');

        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        session_hrate_oversessions(r{idx}, from, to);        
        
    case 'triallen'
        fromobj = findobj('Tag','fromdate'); from = get(fromobj,'String');
        toobj = findobj('Tag','todate'); to = get(toobj,'String');

        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        triallen_influence(r{idx},'from', from, 'to',to);
        set(gcf,'Tag','sessionview');

    case  'psychnums'
        fromobj = findobj('Tag','fromdate'); from = get(fromobj,'String');
        toobj = findobj('Tag','todate'); to = get(toobj,'String');

        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        psychnums_over_time(r{idx},'from', from, 'to',to,'mkover',1,'mark_manips',1);

    case 'dailypsychs'
        fromobj = findobj('Tag','fromdate'); from = get(fromobj,'String');
        toobj = findobj('Tag','todate'); to = get(toobj,'String');

        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        psych_singleday_multi(r{idx},from,to);

        % assumes that the windows generated by this subroutine are the
        % only ones open in addition to sessionsummary.
        newkids = [];
        kids = get(0,'Children'); for k = 1:length(kids),
            if kids(k) ~= 1,
                newkids = horzcat(newkids, kids(k));
                set(kids(k),'Tag','dailypsych');
            end;
        end;

        %      figure__tile(400, 300, 'left2right', newkids);

    case 'pooledpsychs'
        fromobj = findobj('Tag','fromdate'); from = get(fromobj,'String');
        toobj = findobj('Tag','todate'); to = get(toobj,'String');

        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        psych_pooled_oversessions(r{idx},'from',from,'to',to, 'daily_bin_variability', 1);
        set(gcf,'Tag','sessionview','Menubar','figure');

    case 'psychends'
        fromobj = findobj('Tag','fromdate'); from = get(fromobj,'String');
        toobj = findobj('Tag','todate'); to = get(toobj,'String');

        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        psych_endpoints(r{idx},'from',from,'to',to);

    case 'timeout_rate'
        fromobj = findobj('Tag','fromdate'); from = get(fromobj,'String');
        toobj = findobj('Tag','todate'); to = get(toobj,'String');

        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        timeout_rate_oversessions(r{idx},'from',from,'to',to);

    case 'session_hrate'
        fromobj = findobj('Tag','fromdate'); from = get(fromobj,'String');
        toobj = findobj('Tag','todate'); to = get(toobj,'String');

        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        timeout_rate_oversessions(r{idx},'from',from,'to',to);
        
        
    case 'can__baseline'
        v = get(findobj('Tag','can__poolopt'),'value');
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');

        if v == 1, pool = 1; else pool = 0;end;
        psych_plotsingleday_vs_avgwk(r{idx}, 'baseline','maniptype','baseline','pool_baseline', pool);

    case 'can__muscimol'
        vpool = get(findobj('Tag','can__poolopt'),'value');
        vscpt = get(findobj('Tag','can__whichscpt'),'value');
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');

        if vpool == 1, pool = 1; else pool = 0;end;
        if vscpt == 1
            muscdays = rat_task_table(r{idx}, 'action','cannula__muscimol','filter_by_dose',1);
%             midx = find(cell2mat(muscdays(:,3)) < 1);
%             muscdays = muscdays(midx,:);
            muscdays = muscdays(:,1);
            psych_pooled_oversessions(r{idx},'use_dateset','given','given_dateset', muscdays, 'daily_bin_variability', 1);
        else
            psych_plotsingleday_vs_avgwk(r{idx}, 'muscimol','maniptype','muscimol','pool_alldays',pool,'pool_baseline', pool, ...
                'do_preavg', 0);
        end;

    case 'can__nomanip'
        vpool = get(findobj('Tag','can__poolopt'),'value');
        vscpt = get(findobj('Tag', 'can__whichscpt'),'value');
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');

        if vpool == 1, pool = 1; else pool = 0;end;
        if vscpt == 1
            ratrow = rat_task_table(r{idx});
            % start from first day post-baseline
            basedates =  ratrow{4}; str = basedates{2};
            from=yearmonthday(datenum(str2double(str(1:2)),str2double(str(3:4)),str2double(str(5:6)))+1);
            to='999999';
            f = get_files(r{idx}, 'fromdate', from,'todate',to);
            manipdays = rat_task_table(r{idx}, 'action','cannula');
            nondays  = setdiff(f, manipdays(:,1));
            psych_pooled_oversessions(r{idx},'use_dateset','given','given_dateset', nondays, 'daily_bin_variability', 1);
        else
            psych_plotsingleday_vs_avgwk(r{idx},'non-days','maniptype','none','pool_alldays',pool,'pool_baseline',pool, ...
                'do_preavg', 0);
        end;       

    case 'can__saline'
        vpool = get(findobj('Tag','can__poolopt'),'value');
        vscpt = get(findobj('Tag', 'can__whichscpt'),'value');
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');

        if vpool == 1, pool = 1; else pool = 0;end;
            psych_plotsingleday_vs_avgwk(r{idx}, 'saline','maniptype','saline', ...
                'pool_alldays',pool,'pool_baseline', pool, ...
                'do_preavg', 0);
            
      case 'can__sal_musc'
        v = get(findobj('Tag','can__poolopt'),'value');
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');

        if v == 1, pool = 1; else pool = 0;end;
        psych_plotsingleday_vs_avgwk(r{idx}, 'blah','maniptype','plot_pair',...
            'manip_pair1','muscimol','manip_pair2', 'saline', ...
            'pair1_text','Muscimol','pair2_text','Saline', ...
            'pool_alldays',pool,'pool_baseline',pool,...
            'do_preavg', 0, 'write2file', 1);        
        
    case 'can__all'
        v = get(findobj('Tag','can__poolopt'),'value');
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');

        if v == 1, pool = 1; else pool = 0;end;
        psych_plotsingleday_vs_avgwk(r{idx}, 'blah','maniptype','all_three',...    
            'pool_alldays',pool,'pool_baseline',pool,...
            'do_preavg', 0, 'write2file', 1);        

    case 'can__noinf_musc'
        v = get(findobj('Tag','can__poolopt'),'value');
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');

        if v == 1, pool = 1; else pool = 0;end;
        psych_plotsingleday_vs_avgwk(r{idx}, 'blah','maniptype','plot_pair','pool_alldays',pool,'pool_baseline',pool,...
            'do_preavg', 0, 'write2file', 1);

    case 'can__sal_base'
        v = get(findobj('Tag','can__poolopt'),'value');
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');

        if v == 1, pool = 1; else pool = 0;end;
        psych_plotsingleday_vs_avgwk(r{idx}, 'blah','maniptype', 'plot_pair','manip_pair1', 'none', ...
            'pair1_color', [0 0 1], 'pair1_errcolor', [0.8 0 1],'pair1_text','nothing','pool_alldays',pool,...
            'pool_baseline', pool,'do_preavg',0);

    case 'can__singlepsych'
        % date
        h = get(findobj('Tag','dopt'),'SelectedObject');
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');
        if strcmpi(get(h,'Tag'),'dopt_offset')
            dobj = findobj('Tag', 'doffset'); d = str2double(get(dobj,'String'));
            dstr = getdate(d);
        else
            dstr = get(findobj('Tag','date'),'string');
        end;

        v = get(findobj('Tag','can__poolopt'),'value');  if v == 1, pool = 1; else pool = 0;end;
        robj = findobj('Tag','ratname'); r = get(robj,'String'); idx = get(robj,'Value');

        psych_plotsingleday_vs_avgwk(r{idx},dstr,'maniptype','singleday','curvecolor', 'b',...
            'pool_baseline', pool,'do_preavg',0);
end;

%figure(findobj('Tag','sessiondriver'));