function extra_message

try
    setpref('Internet','SMTP_Server','sonnabend.princeton.edu');
    setpref('Internet','E_mail','RegistryMeister@Princeton.EDU');
    
    if strcmp(datestr(now,'mmdd'),'0401')
        try
            message = cell(0);
            message{end+1} = 'C121 has escaped from the animal facility';
            message{end+1} = 'C132 is currently on fire';
            message{end+1} = 'C154 ate his cagemate';
            message{end+1} = 'C155 did not appear to run anywhere, possibly because he was eaten';
            message{end+1} = 'C156 has contracted rat syphilis and has been quarantined';
            message{end+1} = '';
            message{end+1} = 'Please fix these problems in the registry';
            message{end+1} = 'Thanks';
            message{end+1} = 'The Schedule Meister';
            message{end+1} = '';
            message{end+1} = 'This email was automatically generated by the Brody Lab AES';

            sendmail('brody@princeton.edu','Registry Problems Detected',message);
        end
        
        try
            message = cell(0);
            message{end+1} = 'B052 has been endocytosed by his tumor';
            message{end+1} = 'B091 did not appear to run anywhere';
            message{end+1} = 'B091 TechNotes: he lept from the building';
            message{end+1} = 'B107 exploded due to an obstructed bowel';
            message{end+1} = 'B108 has contracted rat syphilis and has been quarantined';
            message{end+1} = 'B110 is currently on fire';
            message{end+1} = '';
            message{end+1} = 'Please fix these problems in the registry';
            message{end+1} = 'Thanks';
            message{end+1} = 'The Schedule Meister';
            message{end+1} = '';
            message{end+1} = 'This email was automatically generated by the Brody Lab AES';

            sendmail('bwen@princeton.edu','Registry Problems Detected',message);
        end
        
        try
            message = cell(0);
            message{end+1} = 'M007 is currently on fire';
            message{end+1} = 'M008 has escaped from the animal facility';
            message{end+1} = 'M009 has contracted rat syphilis and has been quarantined';
            message{end+1} = 'M010 was discovered injecting himself with ketamine';
            message{end+1} = 'M011 ate his cagemate';
            message{end+1} = '';
            message{end+1} = 'Please fix these problems in the registry';
            message{end+1} = 'Thanks';
            message{end+1} = 'The Schedule Meister';
            message{end+1} = '';
            message{end+1} = 'This email was automatically generated by the Brody Lab AES';

            sendmail('mbialek@princeton.edu','Registry Problems Detected',message);
        end
        
        try
            message = cell(0);
            message{end+1} = 'J098 is currently on fire';
            message{end+1} = 'J107 escaped from the animal facility';
            message{end+1} = 'J132 has contracted rat syphilis and has been quarantined';
            message{end+1} = 'J136 exploded due to an obstructed bowel';
            message{end+1} = 'J137 ate his cagemate';
            message{end+1} = '';
            message{end+1} = 'Please fix these problems in the registry';
            message{end+1} = 'Thanks';
            message{end+1} = 'The Schedule Meister';
            message{end+1} = '';
            message{end+1} = 'This email was automatically generated by the Brody Lab AES';

            sendmail('jerlich@princeton.edu','Registry Problems Detected',message);
        end
    end
end
    